// Cities people can live in or dream of. A fixed list instead of a geocoder:
// no API keys, no rate limits, never breaks during the demo.
// lat/lng are CITY-LEVEL only (never someone's exact location).

export type City = {
  name: string;
  country: string;
  tz: string; // IANA time zone
  lat: number;
  lng: number;
  lang: string; // main local language (ISO 639-1)
};

export const CITIES: City[] = [
  { name: 'Atlanta', country: 'United States', tz: 'America/New_York', lat: 33.75, lng: -84.39, lang: 'en' },
  { name: 'New York', country: 'United States', tz: 'America/New_York', lat: 40.71, lng: -74.01, lang: 'en' },
  { name: 'Chicago', country: 'United States', tz: 'America/Chicago', lat: 41.88, lng: -87.63, lang: 'en' },
  { name: 'Los Angeles', country: 'United States', tz: 'America/Los_Angeles', lat: 34.05, lng: -118.24, lang: 'en' },
  { name: 'San Francisco', country: 'United States', tz: 'America/Los_Angeles', lat: 37.77, lng: -122.42, lang: 'en' },
  { name: 'Toronto', country: 'Canada', tz: 'America/Toronto', lat: 43.65, lng: -79.38, lang: 'en' },
  { name: 'Mexico City', country: 'Mexico', tz: 'America/Mexico_City', lat: 19.43, lng: -99.13, lang: 'es' },
  { name: 'Cancún', country: 'Mexico', tz: 'America/Cancun', lat: 21.16, lng: -86.85, lang: 'es' },
  { name: 'São Paulo', country: 'Brazil', tz: 'America/Sao_Paulo', lat: -23.55, lng: -46.63, lang: 'pt' },
  { name: 'Buenos Aires', country: 'Argentina', tz: 'America/Argentina/Buenos_Aires', lat: -34.6, lng: -58.38, lang: 'es' },
  { name: 'London', country: 'United Kingdom', tz: 'Europe/London', lat: 51.51, lng: -0.13, lang: 'en' },
  { name: 'Paris', country: 'France', tz: 'Europe/Paris', lat: 48.86, lng: 2.35, lang: 'fr' },
  { name: 'Lisbon', country: 'Portugal', tz: 'Europe/Lisbon', lat: 38.72, lng: -9.14, lang: 'pt' },
  { name: 'Madrid', country: 'Spain', tz: 'Europe/Madrid', lat: 40.42, lng: -3.7, lang: 'es' },
  { name: 'Barcelona', country: 'Spain', tz: 'Europe/Madrid', lat: 41.39, lng: 2.17, lang: 'es' },
  { name: 'Rome', country: 'Italy', tz: 'Europe/Rome', lat: 41.9, lng: 12.5, lang: 'it' },
  { name: 'Berlin', country: 'Germany', tz: 'Europe/Berlin', lat: 52.52, lng: 13.4, lang: 'de' },
  { name: 'Amsterdam', country: 'Netherlands', tz: 'Europe/Amsterdam', lat: 52.37, lng: 4.9, lang: 'nl' },
  { name: 'Istanbul', country: 'Türkiye', tz: 'Europe/Istanbul', lat: 41.01, lng: 28.98, lang: 'tr' },
  { name: 'Cairo', country: 'Egypt', tz: 'Africa/Cairo', lat: 30.04, lng: 31.24, lang: 'ar' },
  { name: 'Lagos', country: 'Nigeria', tz: 'Africa/Lagos', lat: 6.52, lng: 3.38, lang: 'en' },
  { name: 'Nairobi', country: 'Kenya', tz: 'Africa/Nairobi', lat: -1.29, lng: 36.82, lang: 'sw' },
  { name: 'Cape Town', country: 'South Africa', tz: 'Africa/Johannesburg', lat: -33.92, lng: 18.42, lang: 'en' },
  { name: 'Dubai', country: 'UAE', tz: 'Asia/Dubai', lat: 25.2, lng: 55.27, lang: 'ar' },
  { name: 'Mumbai', country: 'India', tz: 'Asia/Kolkata', lat: 19.08, lng: 72.88, lang: 'hi' },
  { name: 'Delhi', country: 'India', tz: 'Asia/Kolkata', lat: 28.61, lng: 77.21, lang: 'hi' },
  { name: 'Bangkok', country: 'Thailand', tz: 'Asia/Bangkok', lat: 13.76, lng: 100.5, lang: 'th' },
  { name: 'Hanoi', country: 'Vietnam', tz: 'Asia/Bangkok', lat: 21.03, lng: 105.85, lang: 'vi' },
  { name: 'Singapore', country: 'Singapore', tz: 'Asia/Singapore', lat: 1.35, lng: 103.82, lang: 'en' },
  { name: 'Bali', country: 'Indonesia', tz: 'Asia/Makassar', lat: -8.65, lng: 115.22, lang: 'id' },
  { name: 'Hong Kong', country: 'China', tz: 'Asia/Hong_Kong', lat: 22.32, lng: 114.17, lang: 'zh' },
  { name: 'Shanghai', country: 'China', tz: 'Asia/Shanghai', lat: 31.23, lng: 121.47, lang: 'zh' },
  { name: 'Taipei', country: 'Taiwan', tz: 'Asia/Taipei', lat: 25.03, lng: 121.57, lang: 'zh' },
  { name: 'Seoul', country: 'South Korea', tz: 'Asia/Seoul', lat: 37.57, lng: 126.98, lang: 'ko' },
  { name: 'Tokyo', country: 'Japan', tz: 'Asia/Tokyo', lat: 35.68, lng: 139.69, lang: 'ja' },
  { name: 'Kyoto', country: 'Japan', tz: 'Asia/Tokyo', lat: 35.01, lng: 135.77, lang: 'ja' },
  { name: 'Sydney', country: 'Australia', tz: 'Australia/Sydney', lat: -33.87, lng: 151.21, lang: 'en' },
  { name: 'Boston', country: 'United States', tz: 'America/New_York', lat: 42.36, lng: -71.06, lang: 'en' },
  { name: 'Washington DC', country: 'United States', tz: 'America/New_York', lat: 38.91, lng: -77.04, lang: 'en' },
  { name: 'Philadelphia', country: 'United States', tz: 'America/New_York', lat: 39.95, lng: -75.17, lang: 'en' },
  { name: 'Miami', country: 'United States', tz: 'America/New_York', lat: 25.76, lng: -80.19, lang: 'en' },
  { name: 'Orlando', country: 'United States', tz: 'America/New_York', lat: 28.54, lng: -81.38, lang: 'en' },
  { name: 'Charleston', country: 'United States', tz: 'America/New_York', lat: 32.78, lng: -79.93, lang: 'en' },
  { name: 'Savannah', country: 'United States', tz: 'America/New_York', lat: 32.08, lng: -81.09, lang: 'en' },
  { name: 'Detroit', country: 'United States', tz: 'America/Detroit', lat: 42.33, lng: -83.05, lang: 'en' },
  { name: 'Nashville', country: 'United States', tz: 'America/Chicago', lat: 36.16, lng: -86.78, lang: 'en' },
  { name: 'New Orleans', country: 'United States', tz: 'America/Chicago', lat: 29.95, lng: -90.07, lang: 'en' },
  { name: 'Austin', country: 'United States', tz: 'America/Chicago', lat: 30.27, lng: -97.74, lang: 'en' },
  { name: 'Houston', country: 'United States', tz: 'America/Chicago', lat: 29.76, lng: -95.37, lang: 'en' },
  { name: 'Dallas', country: 'United States', tz: 'America/Chicago', lat: 32.78, lng: -96.8, lang: 'en' },
  { name: 'Minneapolis', country: 'United States', tz: 'America/Chicago', lat: 44.98, lng: -93.27, lang: 'en' },
  { name: 'Denver', country: 'United States', tz: 'America/Denver', lat: 39.74, lng: -104.99, lang: 'en' },
  { name: 'Phoenix', country: 'United States', tz: 'America/Phoenix', lat: 33.45, lng: -112.07, lang: 'en' },
  { name: 'Las Vegas', country: 'United States', tz: 'America/Los_Angeles', lat: 36.17, lng: -115.14, lang: 'en' },
  { name: 'San Diego', country: 'United States', tz: 'America/Los_Angeles', lat: 32.72, lng: -117.16, lang: 'en' },
  { name: 'Seattle', country: 'United States', tz: 'America/Los_Angeles', lat: 47.61, lng: -122.33, lang: 'en' },
  { name: 'Portland', country: 'United States', tz: 'America/Los_Angeles', lat: 45.52, lng: -122.68, lang: 'en' },
  { name: 'Anchorage', country: 'United States', tz: 'America/Anchorage', lat: 61.22, lng: -149.9, lang: 'en' },
  { name: 'Honolulu', country: 'United States', tz: 'Pacific/Honolulu', lat: 21.31, lng: -157.86, lang: 'en' },
  { name: 'Vancouver', country: 'Canada', tz: 'America/Vancouver', lat: 49.28, lng: -123.12, lang: 'en' },
  { name: 'Calgary', country: 'Canada', tz: 'America/Edmonton', lat: 51.05, lng: -114.07, lang: 'en' },
  { name: 'Montreal', country: 'Canada', tz: 'America/Toronto', lat: 45.5, lng: -73.57, lang: 'fr' },
  { name: 'Quebec City', country: 'Canada', tz: 'America/Toronto', lat: 46.81, lng: -71.21, lang: 'fr' },
  { name: 'Guadalajara', country: 'Mexico', tz: 'America/Mexico_City', lat: 20.66, lng: -103.35, lang: 'es' },
  { name: 'Monterrey', country: 'Mexico', tz: 'America/Monterrey', lat: 25.69, lng: -100.32, lang: 'es' },
  { name: 'Oaxaca', country: 'Mexico', tz: 'America/Mexico_City', lat: 17.07, lng: -96.73, lang: 'es' },
  { name: 'Puerto Vallarta', country: 'Mexico', tz: 'America/Mexico_City', lat: 20.65, lng: -105.23, lang: 'es' },
  { name: 'Mérida', country: 'Mexico', tz: 'America/Merida', lat: 20.97, lng: -89.62, lang: 'es' },
  { name: 'Tulum', country: 'Mexico', tz: 'America/Cancun', lat: 20.21, lng: -87.47, lang: 'es' },
  { name: 'Playa del Carmen', country: 'Mexico', tz: 'America/Cancun', lat: 20.63, lng: -87.08, lang: 'es' },
  { name: 'Havana', country: 'Cuba', tz: 'America/Havana', lat: 23.11, lng: -82.37, lang: 'es' },
  { name: 'San Juan', country: 'Puerto Rico', tz: 'America/Puerto_Rico', lat: 18.47, lng: -66.11, lang: 'es' },
  { name: 'Santo Domingo', country: 'Dominican Republic', tz: 'America/Santo_Domingo', lat: 18.49, lng: -69.93, lang: 'es' },
  { name: 'Kingston', country: 'Jamaica', tz: 'America/Jamaica', lat: 17.97, lng: -76.79, lang: 'en' },
  { name: 'Guatemala City', country: 'Guatemala', tz: 'America/Guatemala', lat: 14.63, lng: -90.51, lang: 'es' },
  { name: 'Antigua Guatemala', country: 'Guatemala', tz: 'America/Guatemala', lat: 14.56, lng: -90.73, lang: 'es' },
  { name: 'San José', country: 'Costa Rica', tz: 'America/Costa_Rica', lat: 9.93, lng: -84.08, lang: 'es' },
  { name: 'Panama City', country: 'Panama', tz: 'America/Panama', lat: 8.98, lng: -79.52, lang: 'es' },
  { name: 'Bogotá', country: 'Colombia', tz: 'America/Bogota', lat: 4.71, lng: -74.07, lang: 'es' },
  { name: 'Medellín', country: 'Colombia', tz: 'America/Bogota', lat: 6.24, lng: -75.58, lang: 'es' },
  { name: 'Cartagena', country: 'Colombia', tz: 'America/Bogota', lat: 10.39, lng: -75.48, lang: 'es' },
  { name: 'Caracas', country: 'Venezuela', tz: 'America/Caracas', lat: 10.48, lng: -66.9, lang: 'es' },
  { name: 'Quito', country: 'Ecuador', tz: 'America/Guayaquil', lat: -0.18, lng: -78.47, lang: 'es' },
  { name: 'Lima', country: 'Peru', tz: 'America/Lima', lat: -12.05, lng: -77.04, lang: 'es' },
  { name: 'Cusco', country: 'Peru', tz: 'America/Lima', lat: -13.53, lng: -71.97, lang: 'es' },
  { name: 'La Paz', country: 'Bolivia', tz: 'America/La_Paz', lat: -16.49, lng: -68.12, lang: 'es' },
  { name: 'Santiago', country: 'Chile', tz: 'America/Santiago', lat: -33.45, lng: -70.67, lang: 'es' },
  { name: 'Mendoza', country: 'Argentina', tz: 'America/Argentina/Mendoza', lat: -32.89, lng: -68.84, lang: 'es' },
  { name: 'Montevideo', country: 'Uruguay', tz: 'America/Montevideo', lat: -34.9, lng: -56.16, lang: 'es' },
  { name: 'Rio de Janeiro', country: 'Brazil', tz: 'America/Sao_Paulo', lat: -22.91, lng: -43.17, lang: 'pt' },
  { name: 'Salvador', country: 'Brazil', tz: 'America/Bahia', lat: -12.97, lng: -38.5, lang: 'pt' },
  { name: 'Dublin', country: 'Ireland', tz: 'Europe/Dublin', lat: 53.35, lng: -6.26, lang: 'en' },
  { name: 'Edinburgh', country: 'United Kingdom', tz: 'Europe/London', lat: 55.95, lng: -3.19, lang: 'en' },
  { name: 'Manchester', country: 'United Kingdom', tz: 'Europe/London', lat: 53.48, lng: -2.24, lang: 'en' },
  { name: 'Reykjavík', country: 'Iceland', tz: 'Atlantic/Reykjavik', lat: 64.15, lng: -21.94, lang: 'is' },
  { name: 'Porto', country: 'Portugal', tz: 'Europe/Lisbon', lat: 41.15, lng: -8.61, lang: 'pt' },
  { name: 'Seville', country: 'Spain', tz: 'Europe/Madrid', lat: 37.39, lng: -5.98, lang: 'es' },
  { name: 'Valencia', country: 'Spain', tz: 'Europe/Madrid', lat: 39.47, lng: -0.38, lang: 'es' },
  { name: 'Granada', country: 'Spain', tz: 'Europe/Madrid', lat: 37.18, lng: -3.6, lang: 'es' },
  { name: 'Lyon', country: 'France', tz: 'Europe/Paris', lat: 45.76, lng: 4.84, lang: 'fr' },
  { name: 'Marseille', country: 'France', tz: 'Europe/Paris', lat: 43.3, lng: 5.37, lang: 'fr' },
  { name: 'Nice', country: 'France', tz: 'Europe/Paris', lat: 43.7, lng: 7.26, lang: 'fr' },
  { name: 'Brussels', country: 'Belgium', tz: 'Europe/Brussels', lat: 50.85, lng: 4.35, lang: 'fr' },
  { name: 'Geneva', country: 'Switzerland', tz: 'Europe/Zurich', lat: 46.2, lng: 6.14, lang: 'fr' },
  { name: 'Zurich', country: 'Switzerland', tz: 'Europe/Zurich', lat: 47.38, lng: 8.54, lang: 'de' },
  { name: 'Munich', country: 'Germany', tz: 'Europe/Berlin', lat: 48.14, lng: 11.58, lang: 'de' },
  { name: 'Hamburg', country: 'Germany', tz: 'Europe/Berlin', lat: 53.55, lng: 9.99, lang: 'de' },
  { name: 'Vienna', country: 'Austria', tz: 'Europe/Vienna', lat: 48.21, lng: 16.37, lang: 'de' },
  { name: 'Salzburg', country: 'Austria', tz: 'Europe/Vienna', lat: 47.81, lng: 13.06, lang: 'de' },
  { name: 'Milan', country: 'Italy', tz: 'Europe/Rome', lat: 45.46, lng: 9.19, lang: 'it' },
  { name: 'Venice', country: 'Italy', tz: 'Europe/Rome', lat: 45.44, lng: 12.32, lang: 'it' },
  { name: 'Florence', country: 'Italy', tz: 'Europe/Rome', lat: 43.77, lng: 11.26, lang: 'it' },
  { name: 'Naples', country: 'Italy', tz: 'Europe/Rome', lat: 40.85, lng: 14.27, lang: 'it' },
  { name: 'Valletta', country: 'Malta', tz: 'Europe/Malta', lat: 35.9, lng: 14.51, lang: 'en' },
  { name: 'Copenhagen', country: 'Denmark', tz: 'Europe/Copenhagen', lat: 55.68, lng: 12.57, lang: 'da' },
  { name: 'Oslo', country: 'Norway', tz: 'Europe/Oslo', lat: 59.91, lng: 10.75, lang: 'no' },
  { name: 'Stockholm', country: 'Sweden', tz: 'Europe/Stockholm', lat: 59.33, lng: 18.07, lang: 'sv' },
  { name: 'Helsinki', country: 'Finland', tz: 'Europe/Helsinki', lat: 60.17, lng: 24.94, lang: 'fi' },
  { name: 'Prague', country: 'Czechia', tz: 'Europe/Prague', lat: 50.08, lng: 14.44, lang: 'cs' },
  { name: 'Budapest', country: 'Hungary', tz: 'Europe/Budapest', lat: 47.5, lng: 19.04, lang: 'hu' },
  { name: 'Warsaw', country: 'Poland', tz: 'Europe/Warsaw', lat: 52.23, lng: 21.01, lang: 'pl' },
  { name: 'Kraków', country: 'Poland', tz: 'Europe/Warsaw', lat: 50.06, lng: 19.94, lang: 'pl' },
  { name: 'Dubrovnik', country: 'Croatia', tz: 'Europe/Zagreb', lat: 42.65, lng: 18.09, lang: 'hr' },
  { name: 'Split', country: 'Croatia', tz: 'Europe/Zagreb', lat: 43.51, lng: 16.44, lang: 'hr' },
  { name: 'Athens', country: 'Greece', tz: 'Europe/Athens', lat: 37.98, lng: 23.73, lang: 'el' },
  { name: 'Santorini', country: 'Greece', tz: 'Europe/Athens', lat: 36.39, lng: 25.46, lang: 'el' },
  { name: 'Bucharest', country: 'Romania', tz: 'Europe/Bucharest', lat: 44.43, lng: 26.1, lang: 'ro' },
  { name: 'Kyiv', country: 'Ukraine', tz: 'Europe/Kiev', lat: 50.45, lng: 30.52, lang: 'uk' },
  { name: 'Moscow', country: 'Russia', tz: 'Europe/Moscow', lat: 55.76, lng: 37.62, lang: 'ru' },
  { name: 'St. Petersburg', country: 'Russia', tz: 'Europe/Moscow', lat: 59.93, lng: 30.34, lang: 'ru' },
  { name: 'Tbilisi', country: 'Georgia', tz: 'Asia/Tbilisi', lat: 41.72, lng: 44.79, lang: 'ka' },
  { name: 'Marrakech', country: 'Morocco', tz: 'Africa/Casablanca', lat: 31.63, lng: -8.0, lang: 'ar' },
  { name: 'Casablanca', country: 'Morocco', tz: 'Africa/Casablanca', lat: 33.57, lng: -7.59, lang: 'ar' },
  { name: 'Tunis', country: 'Tunisia', tz: 'Africa/Tunis', lat: 36.81, lng: 10.18, lang: 'ar' },
  { name: 'Luxor', country: 'Egypt', tz: 'Africa/Cairo', lat: 25.69, lng: 32.64, lang: 'ar' },
  { name: 'Dakar', country: 'Senegal', tz: 'Africa/Dakar', lat: 14.72, lng: -17.47, lang: 'fr' },
  { name: 'Accra', country: 'Ghana', tz: 'Africa/Accra', lat: 5.6, lng: -0.19, lang: 'en' },
  { name: 'Addis Ababa', country: 'Ethiopia', tz: 'Africa/Addis_Ababa', lat: 9.03, lng: 38.74, lang: 'am' },
  { name: 'Kampala', country: 'Uganda', tz: 'Africa/Kampala', lat: 0.35, lng: 32.58, lang: 'en' },
  { name: 'Kigali', country: 'Rwanda', tz: 'Africa/Kigali', lat: -1.94, lng: 30.06, lang: 'rw' },
  { name: 'Dar es Salaam', country: 'Tanzania', tz: 'Africa/Dar_es_Salaam', lat: -6.79, lng: 39.21, lang: 'sw' },
  { name: 'Zanzibar', country: 'Tanzania', tz: 'Africa/Dar_es_Salaam', lat: -6.17, lng: 39.2, lang: 'sw' },
  { name: 'Johannesburg', country: 'South Africa', tz: 'Africa/Johannesburg', lat: -26.2, lng: 28.05, lang: 'en' },
  { name: 'Tel Aviv', country: 'Israel', tz: 'Asia/Jerusalem', lat: 32.09, lng: 34.78, lang: 'he' },
  { name: 'Jerusalem', country: 'Israel', tz: 'Asia/Jerusalem', lat: 31.77, lng: 35.21, lang: 'he' },
  { name: 'Amman', country: 'Jordan', tz: 'Asia/Amman', lat: 31.95, lng: 35.93, lang: 'ar' },
  { name: 'Beirut', country: 'Lebanon', tz: 'Asia/Beirut', lat: 33.89, lng: 35.5, lang: 'ar' },
  { name: 'Riyadh', country: 'Saudi Arabia', tz: 'Asia/Riyadh', lat: 24.71, lng: 46.68, lang: 'ar' },
  { name: 'Doha', country: 'Qatar', tz: 'Asia/Qatar', lat: 25.29, lng: 51.53, lang: 'ar' },
  { name: 'Abu Dhabi', country: 'UAE', tz: 'Asia/Dubai', lat: 24.45, lng: 54.38, lang: 'ar' },
  { name: 'Tehran', country: 'Iran', tz: 'Asia/Tehran', lat: 35.69, lng: 51.39, lang: 'fa' },
  { name: 'Karachi', country: 'Pakistan', tz: 'Asia/Karachi', lat: 24.86, lng: 67.0, lang: 'ur' },
  { name: 'Lahore', country: 'Pakistan', tz: 'Asia/Karachi', lat: 31.55, lng: 74.34, lang: 'ur' },
  { name: 'Jaipur', country: 'India', tz: 'Asia/Kolkata', lat: 26.91, lng: 75.79, lang: 'hi' },
  { name: 'Varanasi', country: 'India', tz: 'Asia/Kolkata', lat: 25.32, lng: 82.97, lang: 'hi' },
  { name: 'Ahmedabad', country: 'India', tz: 'Asia/Kolkata', lat: 23.02, lng: 72.57, lang: 'gu' },
  { name: 'Pune', country: 'India', tz: 'Asia/Kolkata', lat: 18.52, lng: 73.86, lang: 'mr' },
  { name: 'Goa', country: 'India', tz: 'Asia/Kolkata', lat: 15.49, lng: 73.83, lang: 'hi' },
  { name: 'Bengaluru', country: 'India', tz: 'Asia/Kolkata', lat: 12.97, lng: 77.59, lang: 'kn' },
  { name: 'Hyderabad', country: 'India', tz: 'Asia/Kolkata', lat: 17.39, lng: 78.49, lang: 'te' },
  { name: 'Chennai', country: 'India', tz: 'Asia/Kolkata', lat: 13.08, lng: 80.27, lang: 'ta' },
  { name: 'Kochi', country: 'India', tz: 'Asia/Kolkata', lat: 9.93, lng: 76.27, lang: 'ml' },
  { name: 'Kolkata', country: 'India', tz: 'Asia/Kolkata', lat: 22.57, lng: 88.36, lang: 'bn' },
  { name: 'Kathmandu', country: 'Nepal', tz: 'Asia/Kathmandu', lat: 27.72, lng: 85.32, lang: 'ne' },
  { name: 'Colombo', country: 'Sri Lanka', tz: 'Asia/Colombo', lat: 6.93, lng: 79.86, lang: 'si' },
  { name: 'Dhaka', country: 'Bangladesh', tz: 'Asia/Dhaka', lat: 23.81, lng: 90.41, lang: 'bn' },
  { name: 'Almaty', country: 'Kazakhstan', tz: 'Asia/Almaty', lat: 43.24, lng: 76.95, lang: 'kk' },
  { name: 'Tashkent', country: 'Uzbekistan', tz: 'Asia/Tashkent', lat: 41.3, lng: 69.24, lang: 'uz' },
  { name: 'Samarkand', country: 'Uzbekistan', tz: 'Asia/Samarkand', lat: 39.65, lng: 66.96, lang: 'uz' },
  { name: 'Ulaanbaatar', country: 'Mongolia', tz: 'Asia/Ulaanbaatar', lat: 47.89, lng: 106.91, lang: 'mn' },
  { name: 'Beijing', country: 'China', tz: 'Asia/Shanghai', lat: 39.9, lng: 116.41, lang: 'zh' },
  { name: 'Chengdu', country: 'China', tz: 'Asia/Shanghai', lat: 30.57, lng: 104.07, lang: 'zh' },
  { name: 'Shenzhen', country: 'China', tz: 'Asia/Shanghai', lat: 22.54, lng: 114.06, lang: 'zh' },
  { name: 'Macau', country: 'China', tz: 'Asia/Macau', lat: 22.2, lng: 113.54, lang: 'zh' },
  { name: 'Busan', country: 'South Korea', tz: 'Asia/Seoul', lat: 35.18, lng: 129.08, lang: 'ko' },
  { name: 'Jeju', country: 'South Korea', tz: 'Asia/Seoul', lat: 33.5, lng: 126.53, lang: 'ko' },
  { name: 'Osaka', country: 'Japan', tz: 'Asia/Tokyo', lat: 34.69, lng: 135.5, lang: 'ja' },
  { name: 'Sapporo', country: 'Japan', tz: 'Asia/Tokyo', lat: 43.06, lng: 141.35, lang: 'ja' },
  { name: 'Fukuoka', country: 'Japan', tz: 'Asia/Tokyo', lat: 33.59, lng: 130.4, lang: 'ja' },
  { name: 'Okinawa', country: 'Japan', tz: 'Asia/Tokyo', lat: 26.21, lng: 127.68, lang: 'ja' },
  { name: 'Chiang Mai', country: 'Thailand', tz: 'Asia/Bangkok', lat: 18.79, lng: 98.98, lang: 'th' },
  { name: 'Phuket', country: 'Thailand', tz: 'Asia/Bangkok', lat: 7.88, lng: 98.39, lang: 'th' },
  { name: 'Ho Chi Minh City', country: 'Vietnam', tz: 'Asia/Ho_Chi_Minh', lat: 10.82, lng: 106.63, lang: 'vi' },
  { name: 'Da Nang', country: 'Vietnam', tz: 'Asia/Ho_Chi_Minh', lat: 16.05, lng: 108.2, lang: 'vi' },
  { name: 'Phnom Penh', country: 'Cambodia', tz: 'Asia/Phnom_Penh', lat: 11.56, lng: 104.93, lang: 'km' },
  { name: 'Siem Reap', country: 'Cambodia', tz: 'Asia/Phnom_Penh', lat: 13.36, lng: 103.86, lang: 'km' },
  { name: 'Luang Prabang', country: 'Laos', tz: 'Asia/Vientiane', lat: 19.89, lng: 102.13, lang: 'lo' },
  { name: 'Kuala Lumpur', country: 'Malaysia', tz: 'Asia/Kuala_Lumpur', lat: 3.14, lng: 101.69, lang: 'ms' },
  { name: 'Penang', country: 'Malaysia', tz: 'Asia/Kuala_Lumpur', lat: 5.41, lng: 100.33, lang: 'ms' },
  { name: 'Jakarta', country: 'Indonesia', tz: 'Asia/Jakarta', lat: -6.21, lng: 106.85, lang: 'id' },
  { name: 'Yogyakarta', country: 'Indonesia', tz: 'Asia/Jakarta', lat: -7.8, lng: 110.36, lang: 'id' },
  { name: 'Manila', country: 'Philippines', tz: 'Asia/Manila', lat: 14.6, lng: 120.98, lang: 'tl' },
  { name: 'Cebu', country: 'Philippines', tz: 'Asia/Manila', lat: 10.32, lng: 123.89, lang: 'tl' },
  { name: 'Melbourne', country: 'Australia', tz: 'Australia/Melbourne', lat: -37.81, lng: 144.96, lang: 'en' },
  { name: 'Brisbane', country: 'Australia', tz: 'Australia/Brisbane', lat: -27.47, lng: 153.03, lang: 'en' },
  { name: 'Perth', country: 'Australia', tz: 'Australia/Perth', lat: -31.95, lng: 115.86, lang: 'en' },
  { name: 'Auckland', country: 'New Zealand', tz: 'Pacific/Auckland', lat: -36.85, lng: 174.76, lang: 'en' },
  { name: 'Wellington', country: 'New Zealand', tz: 'Pacific/Auckland', lat: -41.29, lng: 174.78, lang: 'en' },
  { name: 'Queenstown', country: 'New Zealand', tz: 'Pacific/Auckland', lat: -45.03, lng: 168.66, lang: 'en' },
  { name: 'Suva', country: 'Fiji', tz: 'Pacific/Fiji', lat: -18.14, lng: 178.44, lang: 'en' },
  { name: 'Papeete', country: 'French Polynesia', tz: 'Pacific/Tahiti', lat: -17.53, lng: -149.57, lang: 'fr' },
];

// lowercase without accents, so "cancun" finds Cancún and "bogota" finds Bogotá
function plain(s: string): string {
  return s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
}

export function findCity(name: string | undefined): City | undefined {
  if (!name) return undefined;
  return CITIES.find((c) => plain(c.name) === plain(name));
}

export function searchCities(query: string, exclude: string[] = []): City[] {
  const q = plain(query.trim());
  if (!q) return [];
  // cities whose name starts with what you typed come first ("san" → San Diego before Busan)
  return CITIES.filter((c) => !exclude.includes(c.name) && (plain(c.name).includes(q) || plain(c.country).includes(q)))
    .sort((a, b) => Number(!plain(a.name).startsWith(q)) - Number(!plain(b.name).startsWith(q)))
    .slice(0, 5);
}

// Languages people can pick. `speech` is the voice used to read words out loud.
export const LANGUAGES: { code: string; name: string; speech: string }[] = [
  { code: 'en', name: 'English', speech: 'en-US' },
  { code: 'hi', name: 'Hindi', speech: 'hi-IN' },
  { code: 'es', name: 'Spanish', speech: 'es-MX' },
  { code: 'ja', name: 'Japanese', speech: 'ja-JP' },
  { code: 'ko', name: 'Korean', speech: 'ko-KR' },
  { code: 'pt', name: 'Portuguese', speech: 'pt-PT' },
  { code: 'fr', name: 'French', speech: 'fr-FR' },
  { code: 'zh', name: 'Mandarin', speech: 'zh-CN' },
  { code: 'de', name: 'German', speech: 'de-DE' },
  { code: 'it', name: 'Italian', speech: 'it-IT' },
  { code: 'ar', name: 'Arabic', speech: 'ar-SA' },
  { code: 'tr', name: 'Turkish', speech: 'tr-TR' },
  { code: 'th', name: 'Thai', speech: 'th-TH' },
  { code: 'vi', name: 'Vietnamese', speech: 'vi-VN' },
  { code: 'id', name: 'Indonesian', speech: 'id-ID' },
  { code: 'nl', name: 'Dutch', speech: 'nl-NL' },
  { code: 'sw', name: 'Swahili', speech: 'sw-KE' },
  { code: 'bn', name: 'Bengali', speech: 'bn-IN' },
  { code: 'ta', name: 'Tamil', speech: 'ta-IN' },
  { code: 'ur', name: 'Urdu', speech: 'ur-PK' },
  { code: 'ru', name: 'Russian', speech: 'ru-RU' },
  { code: 'pl', name: 'Polish', speech: 'pl-PL' },
  { code: 'el', name: 'Greek', speech: 'el-GR' },
  { code: 'sv', name: 'Swedish', speech: 'sv-SE' },
  { code: 'he', name: 'Hebrew', speech: 'he-IL' },
  { code: 'fa', name: 'Persian', speech: 'fa-IR' },
  { code: 'cs', name: 'Czech', speech: 'cs-CZ' },
  { code: 'hu', name: 'Hungarian', speech: 'hu-HU' },
  { code: 'uk', name: 'Ukrainian', speech: 'uk-UA' },
  { code: 'tl', name: 'Filipino', speech: 'fil-PH' },
  { code: 'ms', name: 'Malay', speech: 'ms-MY' },
  { code: 'da', name: 'Danish', speech: 'da-DK' },
  { code: 'no', name: 'Norwegian', speech: 'nb-NO' },
  { code: 'fi', name: 'Finnish', speech: 'fi-FI' },
  { code: 'ro', name: 'Romanian', speech: 'ro-RO' },
];

export function languageName(code: string | undefined): string {
  // a language someone typed in themselves ("Nepali") is stored as its name
  return LANGUAGES.find((l) => l.code === code)?.name ?? (code && code.length > 3 ? code : 'their language');
}

export function speechLocale(code: string | undefined): string {
  return LANGUAGES.find((l) => l.code === code)?.speech ?? 'en-US';
}

export const INTERESTS = [
  'Film photography', 'Ramen', 'Street food', 'Architecture', 'Music', 'Soccer',
  'Anime', 'Coffee', 'Hiking', 'Fashion', 'Art museums', 'Gaming', 'Cooking',
  'Night markets', 'Cycling', 'K-pop', 'Skateboarding', 'Books', 'Basketball', 'Dance',
];
